apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-caktbyxv
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-caktbyxv:5d694b2a559719dcaf4bbe18b4066ec20283bad9@sha256:465e516ee0e67b7a43020788ce6253fdf30418e781b1eb3659c7832f068df6a1
        name: container-image  
